language: scala

scala:
  - 2.12.1
  - 2.11.7
  - 2.10.5

branches:
  only:
    - master
    - 2.3

notifications:
  email:
    recipients:
      - hacker@zhuchenye.com

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

matrix:
  # scala 2.12 requires java 8
  exclude:
    - scala: 2.12.1
      jdk: openjdk7
    - scala: 2.12.1
      jdk: oraclejdk7
